### ISSUE TITLE
Suggested configuration flags cause unwanted log spew

### ISSUE THREAD

**Issue by mattem** [aspect-build/bazel-super-formatter#10]
The custom configuration flags in the README to disable formatters cause warning log spew as `build` is inherrited by verbs that don't support custom flags, eg:

```
bazel output_base

WARNING: info command does not support starlark options. Ignoring options: [--@aspect_rules_format//format:java_enabled=false]
```

**Comment by alexeagle** [comment]
I saw that too. IMO it's a bazel bug, that there's no bazelrc command like `all` which would be like `common` except never error when the flag isn't understood by the command being run ...

**Comment by mattem** [comment]
Sure, but can it be configured a different way until that issue is resolved?

**Comment by alexeagle** [comment]
Yeah I guess we can just enable the flags for the `run` command? I'll try it in silo first.
