### ISSUE TITLE
How do you imagine this project integrates with editors? 

### ISSUE THREAD

**Issue by mvgijssel** [aspect-build/bazel-super-formatter#25]
### Describe the feature

I'm currently investigating how our team should use Bazel to lint/format files and came across this amazing work! I'm curious how you are imagining formatters built with Bazel to be configured with an editor like VSCode so you get behaviour like "format on save" and inline suggestions.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
That's a great question, I was just answering the same thing for someone at BazelCon. I added a section to the README: https://github.com/aspect-build/bazel-super-formatter/blob/main/README.md#using-from-an-editor
Does that fully answer it? We can discuss more on this issue.

**Comment by mvgijssel** [comment]
>  Since not all engineers will configure their editor

We are in the unique position that everyone using our data engineering stack uses the same editor environment, due to VSCode devcontainer functionality!

> you need to have a pre-commit CI check anyway

You are right, if we have an editor integration or not, we still require a pre-commit hook just in case. Though I'm looking at this from a bit different perspective. 

One thing I notice is that folks, including myself, tend to spend a lot of time formatting their code by hand, despite an auto-formatting pre-commit hook, unless you provide them with an on-save hook in the editor that does it for them. It's one of those habits which is hard to unlearn where the on-save feature helps and makes development (feel) fast. I know this is treating the symptom and not the cause, but still a valid case for our team.

From an implementation perspective, I'm investigating a workflow like this

1. Build the devcontainer docker image for VSCode which during building runs

```bash
bazel build @aspect_rules_format//format
```

2.  The built target outputs the formatter binaries like so (**NOTE: this is a fake build output**)
```bash
devcontainer@3fa34def5196:/workspaces/data-platform$ bazel build @aspect_rules_format//format
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a4903a62-6056-470c-8c14-978f1c633b49
INFO: Found 1 target...
Target //meltano/plugins/extractors/tap_gitlab:tap_gitlab up-to-date:
  /tmp/bazel-data-platform-bin/external/aspect_rules_format/prettier
  /tmp/bazel-data-platform-bin/external/aspect_rules_format/buildifier
  /tmp/bazel-data-platform-bin/external/aspect_rules_format/black
  /tmp/bazel-data-platform-bin/external/aspect_rules_format/gofmt
INFO: Elapsed time: 17.077s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

3. Link/generate VSCode editor config based on the binaries 

Curious if you think something like this is viable from this rule's perspective!

**Comment by alexeagle** [comment]
@mvgijssel sorry I didn't follow up here. Would you like to send a PR for the README here to help others follow what you've done?

**Comment by alexeagle** [comment]
Going to mark this resolved as we have https://github.com/aspect-build/rules_lint#using-with-your-editor
