### ISSUE TITLE
[FR]: Linting

### ISSUE THREAD

**Issue by dudicoco** [aspect-build/bazel-super-formatter#27]
### What is the current behavior?

The tool only does formatting.

### Describe the feature

I wonder why not introduce linting as well? Or is there an existing tool which does "super-linting" and integrates with Bazel?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
Take a look at the design doc at the bottom of the readme. I'd like to do linting next but it's 10x harder and I have no funding source for that.
