### ISSUE TITLE
[Bug]: wrong binaries are being downloaded in Linux/aarch64

### ISSUE THREAD

**Issue by wihtman-videoamp** [aspect-build/bazel-super-formatter#35]
### What happened?

For a **monorepo** managed by **Bazel** and with **bazel super formatter** as a `pre-commit` plugin, we are getting wrong binaries for its dependencies. Specifically when the `pre-commit` hooks for **bazel super formatter** are applied, wrong binaries for `buf` and `buildifier` are being downloaded.

As a consequence, the formatting process ends in a broken state.

It is expected the formatting process to work correctly if the `aarch64` binaries for those tools are downloaded to the system.

**NOTE**: for example when the **bazel super formatter** `pre-commit` hook runs, the `buildifier` binary is being downloaded to `~/.cache/pre-commit/buildifier/linux-amd64-5.1.0/buildifier/buildifier`. Notice the `linux-amd64-5.1.0` directory in the download path.

### Version

Development (host) and target OS/architectures:

`aarch64 GNU/Linux`

Output of `bazel --version`: 

`bazel 6.0.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

`1.0.0` ([Bazel Super Formatteer 1.0.0 version](https://github.com/aspect-build/bazel-super-formatter/releases/tag/v1.0.0))

Language(s) and/or frameworks involved:

**Protocol Buffers** and **Bazel Build files**, but the consequence is that the whole formatting process fails.

### How to reproduce
Working in a **Linux** environment that runs in a `aarch64` architecture if you try to apply the formatter in a repository with modified **Protocol Buffers** or **Bazel BUILD** files (`BUILD` or `BUILD.bazel`), the formatting process will fail since **Bazel Super Formatter** downloads `buf` and `buildifier` `amd64` binaries for a `aarch64` architecture.

**Comment by alexeagle** [comment]
For buf, it happens here:
https://github.com/aspect-build/bazel-super-formatter/blob/main/format/BUILD.bazel#L58-L64
do they have aarch64 binaries published somewhere?

For buildifier it's here https://github.com/aspect-build/bazel-super-formatter/blob/main/format/BUILD.bazel#L45

**Comment by alexeagle** [comment]
I think this is resolved, I came to your monorepo and switched it to rules_lint.
