### ISSUE TITLE
[FR]: bzlmod support?

### ISSUE THREAD

**Issue by manuelnaranjo** [aspect-build/bazel-super-formatter#37]
### What is the current behavior?

No bzlmod support, so it has to be installed outside of MODULE.bazel

### Describe the feature

This repo got forked from bazel-contrib/rules-template before MODULE.bazel support was added, and so it lacks from such features, does it make sense to add it? Would you mind if I contribute it?

**Comment by alexeagle** [comment]
That would be neat. I think this one will require some module extensions to call the repository rules, since there are extra steps needed for users to install the language-specific dependencies for these formatter tools.

**Comment by agluszak** [comment]
I'm working on it
